# This file is used by the pretix team internally to coordinate releases of this plugin
[plugin]
package = "pretix-fontpack-free-inconsolata"
modules = ["pretix_fontpackfree"]
marketplace_name = "fontpack-free-inconsolata"
pypi = false
repository_servers = { origin = "github.com" }
branch_targets = ["origin/master"]

